### ISSUE TITLE
 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by DivisionSi** [panva/node-openid-client#251] opened 2020-04-22 08:50 UTC
I have updated to the latest version and using:

 **node**: 10.16.1
I am getting the following 2 warnings:
  `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`
and
`(Emitted value instead of an instance of Error) Cannot find source file '../source/index.ts': Error: Can't resolve '../source/index.ts' in 'C:\Source_imodelSchemaManagementService\iModelSchemaManagementService\node_modules\@sindresorhus\is\dist'`

Adding 'got' to webpack.config externals solves the issue but I want to avoid that trick.

**Comment by panva** [comment] 2020-04-22 09:20
@DivisionSi why are you running webpack for a node runtime project?

Duplicate of #242, see https://github.com/panva/node-openid-client/issues/242#issuecomment-600545718

**Closed by panva** 2020-04-22 09:20 UTC
Labels: question

**Comment by DivisionSi** [comment] 2020-04-22 09:36
But why is adding it to externals bypassing the warning?
