### ISSUE TITLE
at_hash mismatch for Yahoo IdP

### ISSUE THREAD

**Issue by DanPM** [panva/node-openid-client#90] opened 2018-04-20 12:53 UTC
Hello,

The following piece of code gets me an at_hash mismatch error when using Yahoo as IdP. 
When I do reponse_type='id_token', I'm keep being redirected to consent page from the callback endpoint.
Any help is appreciated.

```
const path       = require('path');
const logger     = require('morgan');
const bodyParser = require('body-parser');
const express    = require('express');
const session    = require('express-session');
const favicon    = require('serve-favicon');


const passport   = require('passport');
const { Issuer } = require('openid-client');

Issuer.discover('https://api.login.yahoo.com')
    .then(function (issuer) {
        console.log('Discovered issuer %s', issuer);
        const client = new issuer.Client(
            { client_id:              'client'
                , client_secret:         'client_secret'
                ,id_token_signed_response_alg: 'ES256'
            }
        );
        client.CLOCK_TOLERANCE = 5;
        const params = {
            redirect_uri:           'http://127.0.0.1/callback',
            response_type: 'id_token'
        };
        passport.use(
            'oidc'
            , new Strategy(
                { client
                    , params
                    , passReqToCallback
                    , usePKCE
                }
                , (tokenset,  done) => {
                console.log('tokenset',     tokenset);
        console.log('access_token', tokenset.access_token);
        console.log('id_token',     tokenset.id_token);
        console.log('claims',       tokenset.claims);
        console.log('userinfo',     userinfo);
        return done(null, done);
    }
        )
        );
        app.use(passport.initialize());
        app.use(passport.session());

    });

const { Strategy } = require('openid-client');

const passReqToCallback = false;

const usePKCE = true;

passport.serializeUser(
    function(user, done) {
        done(null, user);
    }
);
passport.deserializeUser(
    function(obj, done) {
        done(null, obj);
    }
);

const index  = require('./routes/index');
const blabla = require('./routes/blabla');
const users  = require('./routes/users');

const app = express();

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

app.use(favicon(path.join(__dirname, 'static', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'static')));


app.use(
    session(
        { cookie:            { httpOnly: true }
            , secret:            "long random string"
            , resave:            false
            , saveUninitialized: true
        }
    )
);

function isAuthenticated(req, res, next){
    if(req.isAuthenticated()){
        next();
    } else{
        res.redirect("/");
    }
}

app.use('/',       index);
app.use('/blabla', blabla);
app.use('/users',  isAuthenticated, users);

app.get(
    '/login'
    , passport.authenticate(
        'oidc'
    )
);

app.get(
    '/callback'
    , passport.authenticate(
        'oidc'
        , { callback: true
            , successReturnToOrRedirect: '/users'
        }
    )
);

app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
});

app.use(function(err, req, res, next) {
    // set locals, only providing error in development
    res.locals.message = err.message;
    res.locals.error = req.app.get('env') === 'development' ? err : {};

    // render the error page
    res.status(err.status || 500);
    res.render('error');
});

module.exports = app;
```

ERROR:

```
at_hash mismatch

AssertionError [ERR_ASSERTION]: at_hash mismatch
    at Client.validateIdToken (C:\Users\danP\nodejs_apps\AccessManagerOpenIDYahoo\node_modules\openid-client\lib\client.js:501:7)
    at grant.then.then.tokenset (C:\Users\danP\nodejs_apps\AccessManagerOpenIDYahoo\node_modules\openid-client\lib\client.js:322:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by panva** [comment] 2018-04-20 13:14
First of all, the OP should not be returning an access_token for `response_type=id_token` at all.

Second, how do you even get an implicit callback on a GET route? `id_token` is an implicit response and the params must be received in a fragment, which your server won't receive.

In either case - post the id_token and access_token values you're getting. I'm certain the calculated `at_hash` is incorrect (IdP issue).

**Comment by DanPM** [comment] 2018-04-20 17:06
First of all, thank you for the kind explanations.

> response_type=code for a backend integration, do you have a reason to use implicit flow?
It doesn't require the back channel which I don't need for my PoC.  Also it doesn't require skills in debugging nodejs to see what's going in the back channel (which I don't have). 

> Post the id_token and access_token values you're getting. I'm certain the calculated at_hash is incorrect (IdP issue).

I don't know how. It never get to this point: 
Any tips? 
```
                console.log('tokenset',     tokenset);
        console.log('access_token', tokenset.access_token);
        console.log('id_token',     tokenset.id_token);
        console.log('claims',       tokenset.claims);
```

response_mode=form_post has to be supported by IdP right? I don't see any indication that Yahoo supports it.
I will try now the repost idea and let you know.

**Comment by panva** [comment] 2018-04-21 08:39
> I don't know how. Any tips?

Unfortunately I haven't gotten around to DEBUG support just yet (PR welcome). But you can do this to

1) make openid-client use request library instead of got
2) wrap request library to log all request and response bodies headers etc.

```
# shell
$ npm install request request-debug

# code
const { Issuer } = require('openid-client');
const request = require('request');
require('request-debug')(request);
Issuer.useRequest();


// ... the rest of your code
```

You can revert this afterwards.

**Comment by DanPM** [comment] 2018-04-21 12:27
Thanks for shedding some light. 

The implicit workflow I got it working using the repost code that you kindly shared.  Thank you for that.

For authorization code still getting at_hash mismatch 

`     body: '{"access_token":"_urouyWZ41oNWOFAiKlM59Py4pfJcwGQacmDxHcUDpWO75Q8UCnSbEYCt40zidkH7PoycpekRMAppZGD8ziHVQXIfEq3gHKC9LWgoYOeAK8FSVUMRH_G5Vl0WO2lMz7CVtHXeVjrd7dhSog3ffFLUzcp99KnuAtysAJ4dfwi498YVfdJyO.foklcHl92GVL7L0u5JeAjdhXE5hnKKSywPisnfyt_c1IG1H4JLR16x9zjNsqr34rBd_PviH7d_w6nZ.9bgxx4V8eyJk0pYDf6yQn_9BUSLMikfDG.MPJ4bBDtVHA7xD6aM.VzBgc6nHrn6g7mAzcyfmuVZCVznDeeeEL0XaQPQ1qqGkBGZqvzIEulGl4gyEXzu6cDcLIMmzH03mtO7rMlSD794RyQFPvplaLA13V3EYxUwmn2Bt2TbVFr5MVRZtV6WhFYSEqymlKY0f2dPKnh_Kl8q8dikZTr.q8.sJ9F1S5_ksZgIzC3F_n5ATJkowRe6pEQIuEofyNqC48LGneRLU4zTQqTdhLEJq0xVpJl7e6dAIv9Yw1I8NG_AGXp4xBnZ9LVXkxNRX4i0EIOeBPYbKJ_jcOxH.PZdBfVVnOuzguKL36.SxD6PPKgPmo_hZctUZ9V2Nd4aNVVgrKPVZ_Nx.PSZbXyKP93Wqy_e9yd5JpS9PpeO3lEq.L2sAFygI4SVK.O28hYU0sDhn0CEk7xz2VLlse4OGEuCmzdL4O8bYQnrgBXyQ5qzCtlGdmAk00KKKnGR20LLJIzd1YQ_fW2i7g16pH9JwqZ4wTEDcjDQgInEG8hjOwJvC6TURDHK0oEzZzFzKwl0sJ515h5U04LGmN2ywJ8pdG7a2RTb8TyqbhPJtIT5oAaa3QYoeIlx105JyqYZFn1Yu2nsa1IL_6CJNbx27cSHP_lC.GQ3aH23yIT_wOmkI77IEtaWkPGqpN8QN2B9K4JfALEMptncPS_Ev70n0_ptgLP9wSTu0r6HAYKYnvlt2KYt5mvH88Uiy072Ukdc7QJ5j7ASxLz5Kk2mplVLdqYB.PrEC2bvzJOjkwjkYzaKhBEEUo47Q--","refresh_token":"AHnZ2Foq3nACCq6mrP9jJGRruI.fSLIQLAHbsPFfXXTMvj.otGHdhBc-","expires_in":3600,"token_type":"bearer","xoauth_yahoo_guid":"KVOGUWQQIL3OWYF5SYVKFDGMRU","id_token":"eyJhbGciOiJFUzI1NiIsImtpZCI6IjM0NjZkNTFmN2RkMGM3ODA1NjU2ODhjMTgzOTIxODE2YzQ1ODg5YWQifQ.eyJhdF9oYXNoIjoiS2x4RHpsY2EzVFBobFlweEFDVm5nZz09Iiwic3ViIjoiS1ZPR1VXUVFJTDNPV1lGNVNZVktGREdNUlUiLCJpc3MiOiJodHRwczovL2FwaS5sb2dpbi55YWhvby5jb20iLCJsb2NhbGUiOiJlbi1VUyIsImdpdmVuX25hbWUiOiJkYW4iLCJub25jZSI6IiIsImF1ZCI6ImRqMHlKbWs5TVRCMmVGUlhTbUpPTkZOWUptUTlXVmRyT1ZVemFFbFNWbEpNVFRKTmJXTkhiemxOUVMwdEpuTTlZMjl1YzNWdFpYSnpaV055WlhRbWVEMDNNZy0tIiwiYXV0aF90aW1lIjoxNTI0MzEzMDgzLCJuYW1lIjoiZGFuIHBhbmFpdG9haWEiLCJzZXNzaW9uX2V4cCI6MTUyNTUyMjY4MywiZXhwIjoxNTI0MzE2NjkyLCJpYXQiOjE1MjQzMTMwOTIsImZhbWlseV9uYW1lIjoicGFuYWl0b2FpYSJ9.Mgh434xmd2o94LjvLcgDj46PkYIwGV8V1CYaCDX5Oo6T3pBGx_Y-YLiTstoWqPERqvN4jq1mX_QTSNE5-5uSPQ"}' } }`

**Comment by panva** [comment] 2018-04-21 12:34
The correct at_hash value for the access_token provided is `KlxDzlca3TPhlYpxACVngg`, what Yahoo IdP provides is `KlxDzlca3TPhlYpxACVngg==`, the problem is they're using base64 to represent the hash instead of base64url. I'm going to go ahead and close this as this is an IdP mistake.

**Closed by panva** 2018-04-21 12:34 UTC
Labels: question

**Comment by DanPM** [comment] 2018-04-21 23:28
any way to circumvent this mismatch?
I tried 3 IdPs so far, the only one that actually worked without any problems was google. 
There are  lots of IdPs out there, but seems that only a few implement the specs to the letter.

**Comment by panva** [comment] 2018-04-22 06:15
> any way to circumvent this mismatch?

Using an IdP that does not do it’s own interpretation of the specs. Preferably a certified one, that ensures interoperability of software components.

You should be raising issues with your idps primarily, requiring headers or providing wrong hashes, all this is increasing the entry cost to developers on their platforms. Ask them to stick to the spec, feature flag conformant behaviors for new clients. 

Else you’re left with using an oauth2 client and implementing id token validation of your own.
