### ISSUE TITLE
Dynamic Registration Typescript Error

### ISSUE THREAD

**Issue by jwheeler-gs** [panva/node-openid-client#255] opened 2020-05-01 15:46 UTC
There seems to be a type definition problem with `TypeOfGenericClient<Client>`. The `register` method is declared as `static` and cannot be accessed from a `Client` instance according to the TS definition. Given the code below:
```
import { Issuer } from 'openid-client';
const issuer = new Issuer({
          issuer: 'http://example.com',
          registration_endpoint: 'https://op.example.com/client/registration',
        });
const client = await issuer.Client.register(this.metadata);
```

I am getting this error:
```
Property 'register' does not exist on type 'TypeOfGenericClient<Client>'. ts(2339)
```

I'm using the code the same way as the javascript example in this repo's tests folder. I'm not sure if I need to do something differently for Typescript or not. Is there an example somewhere of how to do dynamic registration differently for typescript usage of this library? It looks like in TS land the `register` method is static instead of being an instance member?
```
static register(metadata: object, other?: RegisterOther & ClientOptions): Promise<Client>;
```

**Comment by jwheeler-gs** [comment] 2020-05-01 16:00
As a very hacky workaround to be able to compile right now, I'm currently doing the following:

```
interface MyClient extends TypeOfGenericClient<Client> {
  register: typeof Client.register;
}

client = await (issuer.Client as MyClient).register(this.metadata);
```

**Comment by panva** [comment] 2020-05-01 16:16
Yeah i’ll see to get it fixed. Thanks for raising this

**Comment by panva** [comment] 2020-05-02 08:18
Actually, this is a duplicate of #232, i welcome anyone with the TS skills to add this to the list of things to [fix](https://github.com/panva/node-openid-client/issues/232#issuecomment-591293420)

**Closed by panva** 2020-05-02 08:18 UTC
Labels: bug
