### ISSUE TITLE
index.d.ts causing build error.

### ISSUE THREAD

**Issue by lexyfeitopayrix** [panva/node-openid-client#427] opened 2021-11-12 19:29 UTC
**Describe the bug**
When running `tsc` to build the project I get a build error coming from `openid-client/types/index.d.ts`. 

``
node_modules/openid-client/types/index.d.ts:15:5 - error TS2344: Type '"timeout" | "lookup" | "headers" | "key" | "ca" | "cert" | "passphrase" | "pfx" | "agent" | "crl"' does not satisfy the constraint '"ho
st" | "path" | "auth" | "timeout" | "headers" | "key" | "method" | "protocol" | "rejectUnauthorized" | "ca" | "cert" | "passphrase" | "pfx" | "createConnection" | "agent" | ... 25 more ... | "servername"'.
  Type '"lookup"' is not assignable to type '"host" | "path" | "auth" | "timeout" | "headers" | "key" | "method" | "protocol" | "rejectUnauthorized" | "ca" | "cert" | "passphrase" | "pfx" | "createConnectio
n" | "agent" | ... 25 more ... | "servername"'.
``

And it is being caused by
`export type HttpOptions = Partial<Pick<https.RequestOptions,
    | 'agent'
    | 'ca'
    | 'cert'
    | 'crl'
    | 'headers'
    | 'key'
    | 'lookup',
    | 'passphrase'
    | 'pfx'
    | 'timeout'
    >>`

I am using `"typescript": "^4.1.3",`

Any idea what could cause this, any other information need to determine the problem?

**Environment:**
 - openid-client version: [v5.0.2]
 - node version: [v14.18.1]
 - typescript: [v4.1.3]

**Comment by panva** [comment] 2021-11-12 19:38
Update your @types/node.

**Comment by panva** [comment] 2021-11-12 19:39
Also. A duplicate of #424

**Closed by panva** 2021-11-12 19:38 UTC
Labels: triage
